[package]
name = "lockbell"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/makcandrov/lockbell"
homepage = "https://github.com/makcandrov/lockbell"
documentation = "https://docs.rs/lockbell"
description = "An RwLock that rings back when contention clears."
license = "MIT OR Apache-2.0"
keywords = ["lock", "bell", "rwlock"]
categories = ["concurrency", "data-structures"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
parking_lot = { version = "0.12.5", default-features = false }

[features]
arc_lock = ["parking_lot/arc_lock"]
